apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: affine
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "32Mi"
              cpu: "5m"
            limits:
              memory: "64Mi"
              cpu: "100m"
      restartPolicy: Always
