apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-task-runners-config
  namespace: n8n
data:
  n8n-task-runners.json: |
    {
      "task-runners": [
        {
          "runner-type": "javascript",
          "health-check-server-port": "5681",
          "env-overrides": {}
        },
        {
          "runner-type": "python",
          "health-check-server-port": "5682",
          "env-overrides": {
            "N8N_RUNNERS_STDLIB_ALLOW": "*"
          }
        }
      ]
    }
